language: go

go:
  - 1.13.x

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_script:
  #  - psql -c 'create database postgres;' -U postgres
  - psql -c "ALTER USER postgres PASSWORD 'root';" -U postgres

install:
  - go build ./...

script:
  - go test ./... -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN


