// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "walletAPI/pkg/entity"
import mock "github.com/stretchr/testify/mock"

// TransactionUsecase is an autogenerated mock type for the TransactionUsecase type
type TransactionUsecase struct {
	mock.Mock
}

// MakeDeposit provides a mock function with given fields: a, amount
func (_m *TransactionUsecase) MakeDeposit(a *entity.Account, amount float64) error {
	ret := _m.Called(a, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Account, float64) error); ok {
		r0 = rf(a, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MakeWithdrawal provides a mock function with given fields: a, amount
func (_m *TransactionUsecase) MakeWithdrawal(a *entity.Account, amount float64) error {
	ret := _m.Called(a, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Account, float64) error); ok {
		r0 = rf(a, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
