on: ["push","pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: postgres
          postgresql user: postgres
          postgresql password: root

      - name: Setup Go for use with actions
        uses: actions/setup-go@v1.1.1
        with:
          go-version: '1.13'

      - uses: actions/checkout@master

      - name: run test-coverage
        run: |
          go build ./...
          go test ./... -v -covermode=count -coverprofile=coverage.out

      - name: Coveralls
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage.out

