on: ["push","pull_request"]

name: Test Coverage

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: postgres
          postgresql user: postgres
          postgresql password: root

      - name: Set up Go 1.13
        uses: actions/setup-go@v1.1.1
        with:
          go-version: '1.13'

      - name: Check out code
        uses: actions/checkout@master

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go get github.com/schrej/godacov

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: Run test-coverage and send to Codacy
        run: |
          go get github.com/schrej/godacov
          go test ./... -coverprofile=coverage.out
          $(go env GOPATH)/bin/godacov -t ${{ secrets.CODACY_PROJECT_TOKEN }} -r ./coverage.out -c ${{ github.sha }}
          
      - name: Codecov report
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          bash <(curl -s https://codecov.io/bash)




